### ISSUE TITLE
Can you please include a screen shot on how it will look like? Thank you.

### ISSUE THREAD

**Issue by ariesbrylle-bms** [CiftciCagatay/react-native-gantt-chart#3]

**Comment by sparesh21** [comment]
![Screenshot_20210219-210255](https://user-images.githubusercontent.com/37034349/108525347-fd783680-72f5-11eb-9921-7fb905a2d711.png)


@ariesbrylle-bms Its something looks like this.

**Comment by phantom1299** [comment]
@sparesh21 thanks, closing this.
